// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OperationSmurf.Models;

namespace OperationSmurf.Migrations.Section
{
    [DbContext(typeof(SectionContext))]
    [Migration("20190303232628_troubleSection")]
    partial class troubleSection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OperationSmurf.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName");

                    b.Property<int>("Period");

                    b.Property<string>("TeacherName");

                    b.HasKey("Id");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("OperationSmurf.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("LastName");

                    b.Property<int>("Period1");

                    b.Property<int>("Period2");

                    b.Property<int>("Period3");

                    b.Property<int>("Period4");

                    b.Property<int>("Period5");

                    b.Property<int>("Period6");

                    b.Property<int?>("SectionId");

                    b.Property<int>("StudentId");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("OperationSmurf.Models.Student", b =>
                {
                    b.HasOne("OperationSmurf.Models.Section")
                        .WithMany("Roster")
                        .HasForeignKey("SectionId");
                });
#pragma warning restore 612, 618
        }
    }
}
